name: Sealy CI
# Silly CI? Seaaaaly CI Siili CI? 0Ð”0

# On PR -> run CI
# On Merge -> TBD

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main] # target is main
    types: [opened, synchronize] # on open, new commit to source

jobs:
  migration:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.PG_TEST_U_P_D }}
          POSTGRES_PASSWORD: ${{ secrets.PG_TEST_U_P_D }}
          POSTGRES_DB: ${{ secrets.PG_TEST_U_P_D }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PG_TEST_URL: postgresql+psycopg://${{ secrets.PG_TEST_U_P_D }}:${{ secrets.PG_TEST_U_P_D }}@localhost:5432/${{ secrets.PG_TEST_U_P_D }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # Don't remove pytest from the optional dep!!
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[test]

      - name: Run tests
        run: pytest
